#!/usr/bin/env python

import re
import sys

from subprocess import *

p = Popen("pylint --rcfile=/home/anr/src/pdrepos01/toolchains/scons/misc/pylint.rc -r n %s" %
              (disable, sys.argv[1]), shell = True, stdout = PIPE).stdout

for line in p.readlines():
    match = re.search("\\[([WE])(, (.+?))?\\]", line)
    if match:
        kind = match.group(1)
        func = match.group(3)

        if kind == "W":
            msg = "Warning"
        else:
            msg = "Error"

        if func:
            line = re.sub("\\[([WE])(, (.+?))?\\]",
                          "%s (%s):" % (msg, func), line)
        else:
            line = re.sub("\\[([WE])?\\]", "%s:" % msg, line)
    print line,

p.close()
