#! /bin/sh
#
#    $Id$
#

cd $HOME

debug=

case $1 in
    -c|--clear)
	cat /dev/null | xrdb -load
	;;
    -n)
	debug=-n
	;;
esac

ostype=`uname -s | tr A-Z a-z`
export REAL_DPI=$(xrandr --current | perl -ne '/connected primary (\d+)x(\d+).* (\d+)mm x (\d+)mm/ && printf "%d\n", sqrt($1**2+$2**2)*25.4/sqrt($3**2+$4**2)')
if [ -z "$REAL_DPI" ]; then
    echo "REAL_DPI was empty. Using 157"
    export REAL_DPI=157
fi

export STEP_DPI=$[REAL_DPI/24*24]

if [ -f $HOME/.Xresources ]; then 
    xrdb $debug -merge \
	-DHOME=$HOME \
	-DSETUPTYPE_$SETUPTYPE \
	-DREAL_DPI=$REAL_DPI \
	-DSTEP_DPI=$STEP_DPI \
	-DOS_$ostype \
	-cpp 'cpp' \
	$HOME/.Xresources
fi

if [ -f $HOME/.Xresources.m4 ]; then
    xrdb $debug -merge \
	-DHOME=$HOME \
	-DSETUPTYPE_$SETUPTYPE \
	-DREAL_DPI=$REAL_DPI \
	-DSTEP_DPI=$STEP_DPI \
	-DOS_$ostype \
	-cpp 'm4 -P' \
	$HOME/.Xresources.m4
fi

for file in $HOME/.Xresources.d/*; do
    if [ -f "$file" ]; then
	case $file in
	    *~)
		: ignore
		;;
	    *.m4)
		xrdb $debug -merge \
		    -DHOME=$HOME \
		    -DSETUPTYPE_$SETUPTYPE \
		    -DSETUPTYPE=$SETUPTYPE \
		    -DREAL_DPI=$REAL_DPI \
		    -DSTEP_DPI=$STEP_DPI \
		    -DOS_$ostype \
		    -DOS=$ostype \
		    -cpp 'm4 -P' \
		    $file
		;;
	    *.sh)
		bash $file | xrdb $debug -merge \
		    -DHOME=$HOME \
		    -DSETUPTYPE_$SETUPTYPE \
		    -DSETUPTYPE=$SETUPTYPE \
		    -DREAL_DPI=$REAL_DPI \
		    -DSTEP_DPI=$STEP_DPI \
		    -DOS_$ostype \
		    -DOS=$ostype \
		    -cpp 'cpp' \
		    -
		;;
	    *.cpp)
		xrdb $debug -merge \
		    -DHOME=$HOME \
		    -DSETUPTYPE_$SETUPTYPE \
		    -DSETUPTYPE=$SETUPTYPE \
		    -DREAL_DPI=$REAL_DPI \
		    -DSTEP_DPI=$STEP_DPI \
		    -DOS_$ostype \
		    -DOS=$ostype \
		    -cpp 'cpp' \
		    $file
		;;
	    *)
		echo "reset-resources: '$file' not in known format" >&2
		;;
	esac
    fi
done
