#!/bin/bash

export auto_proxy=""
export no_proxy="localhost,127.*,10.*,192.168.*,169.254.*"

#case "$DESKTOP_SESSION" in
#    i3)
#        :
#        ;;
#esac

msg() {
    local template="$1"; shift
    printf "$template\n" ${1+"$@"} >&2
}

shopt -s nullglob

setxkbmap -option 'caps:escape'
setxkbmap no

$HOME/.scripts/xsetup.sh

msg "= Running session [$*]..."
exec "$@"
