#!/bin/bash

export auto_proxy=""

if [ -z "$GNOME_KEYRING_PID" ]; then
    eval $(gnome-keyring-daemon --start)
    export GNOME_KEYRING_SOCKET
    export GNOME_KEYRING_PID
fi

case "$DESKTOP_SESSION" in 
    xmonad)
        gnome-settings-daemon &
        ;;
    i3)
        #unity-settings-daemon &
        ;;
esac

msg() {
    local template="$1"; shift
    printf "$template\n" ${1+"$@"} >&2
}

shopt -s nullglob

msg "Starting session [%s]" "DESKTOP_SESSION"

num_monitors=$(DISPLAY=:0 xrandr -q | grep ' connected' | wc -l)

case "$num_monitors" in
    1)
        msg "skip dpi voodoo"
        ;;
    *)
        for script in $HOME/.config/start-session/common.d/*.sh; do
            if [ -x "$script" ]; then
                msg "= Running common script: %s" "$script"
                "$script" "$DESKTOP_SESSION"
            fi
        done
        ;;
esac


#export QT_DEVICE_PIXEL_RATIO=auto
export no_proxy="localhost,127.*,10.*,192.168.*,169.254.*"
setxkbmap -option 'caps:escape'
setxkbmap no

msg "= Running session [$*]..."
exec "$@"
